'use strict';

/**
 * Module dependencies.
 */

var fs = require('fs');
var utils = require('engine-utils');


/**
 * Requires cache.
 */


var requires = {};


/**
 * Handlebars support.
 */

var engine = utils.fromStringRenderer('handlebars');


/**
 * Handlebars string support. Render the given `str` and invoke the callback `cb(err, str)`.
 *
 * ```js
 * var engine = require('engine-handlebars');
 * engine.render('{{name}}', {name: 'Jon Schlinkert'}, function (err, content) {
 *   console.log(content); //=> 'Jon Schlinkert'
 * });
 * ```
 *
 * @param {String} `str`
 * @param {Object|Function} `options` or callback.
 *     @property {Object} `cache` enable template caching
 *     @property {String} `filename` filename required for caching
 * @param {Function} `cb` callback function.
 * @api public
 */

engine.render = function render(str, options, cb) {
  var handlebars = requires.handlebars || (requires.handlebars = require('handlebars'));
  if (typeof options === 'function') {
    cb = options;
    options = {};
  }

  var opts = options || {};

  // cache requires .filename
  if (opts.cache && !opts.filename) {
    return cb(new Error('the "filename" option is required for caching'));
  }

  try {
    var path = options.filename;

    for (var partial in opts.partials) {
      handlebars.registerPartial(partial, opts.partials[partial]);
    }
    for (var helper in opts.helpers) {
      handlebars.registerHelper(helper, opts.helpers[helper]);
    }

    var tmpl = opts.cache ? utils.cache[path] || (utils.cache[path] = handlebars.compile(str)) : handlebars.compile(str);
    cb(null, tmpl(opts), '.html');
  } catch (err) {
    cb(err);
  }
};


/**
 * Synchronously render Handlebars or templates.
 *
 * @param  {Object} `str` The string to render.
 * @param  {Object} `options` Object of options.
 *   @option {Object} `settings` Settings to pass to Lo-Dash.
 *   @option {Object} `delims` Template delimiters, generated by [delims]
 *   @option {Object} `imports` Template helpers to pass to Lo-Dash.
 * @return {String} Rendered string.
 * @api public
 */

engine.renderSync = function renderSync(str, options) {
  var handlebars = requires.handlebars || (requires.handlebars = require('handlebars'));
  var opts = options || {};

  try {
    var path = options.filename;
    var tmpl = opts.cache ?
      utils.cache[path] || (utils.cache[path] = handlebars.compile(str)) :
      handlebars.compile(str);

    return tmpl(opts);
  } catch (err) {
    return err;
  }
};


/**
 * Handlebars file support. Render a file at the given `path` and callback `cb(err, str)`.
 *
 * @param {String} `path`
 * @param {Object|Function} `options` or callback function.
 * @param {Function} `cb` callback function
 * @api public
 */

engine.renderFile = function renderFile(path, options, cb) {
  if (typeof options === 'function') {
    cb = options;
    options = {};
  }

  var key = path + ':string';
  var opts = options || {};

  try {
    opts.filename = path;

    var str = opts.cache ?
      utils.cache[path] || (utils.cache[path] = fs.readFileSync(path, 'utf8')) :
      fs.readFileSync(path, 'utf8');

    engine.render(str, opts, cb);
  } catch (err) {
    cb(err);
  }
};

engine.cache = {};


/**
 * Express support.
 */

engine.__express = engine.renderFile;


/**
 * Expose `engine`
 */

module.exports = engine;